[workspace]
members = ["ant-core", "ant-cli"]
resolver = "2"

[patch.crates-io]
ant-protocol = { git = "https://github.com/WithAutonomi/ant-protocol", rev = "d4ea7f69f49ad7be5b80e59639c42d568c916470" }
saorsa-core = { git = "https://github.com/WithAutonomi/saorsa-core", rev = "52bb3819e6a18872d530539942be600f644fa24f" }
saorsa-transport = { git = "https://github.com/WithAutonomi/saorsa-transport", rev = "ac3c5d986f97ff71ed305c9d4436956637040671" }
saorsa-pqc = { git = "https://github.com/saorsa-labs/saorsa-pqc", rev = "6d57e9dd73d537182fe85b0050e809a224f21154" }
evmlib = { git = "https://github.com/WithAutonomi/evmlib", rev = "c80b7c7aee11bb62503b00d8b41e08da1a13039d" }
