import assert from "node:assert/strict";
import test from "node:test";
import { brotliDecompressSync } from "node:zlib";
import { blake3 } from "@noble/hashes/blake3.js";
import { decryptSelfEncryptedChunk, downloadPublicFile } from "./file.js";
import { bytesToHex, hexToBytes } from "./protocol.js";

// Generated by self_encryption 0.36 from
// "browser whole-file fixture\n" repeated 160 times. This is a compatibility
// vector, not a JavaScript-generated round trip.
const chunks = [
  {
    index: 0,
    dst_hash: "c024c6884a2f39be7ba07c3d9636efedeb94df7397fcd38bac5ae904643c5cc9",
    src_hash: "a049deadbb9eb8ef8102a99698ec8484ba4ba9f1d82089af28b31d70783aae8b",
    src_size: 1440,
    encrypted:
      "7508d7886030b903dce0178555d3df9115240fb3efe6029c4b57c05f84d82b85aedb898c09345c65a55dc32ff125e6af96ceab",
  },
  {
    index: 1,
    dst_hash: "350a88e6eb0b2a3e774107a212a272b4191af69ca4366a4b91f5a1e5872c459a",
    src_hash: "a15219e6c26233304a4e733946b97282c2d7ac270e6bd31b7ebdd22ee428cbab",
    src_size: 1440,
    encrypted:
      "5244d1869387ef32f8bec83ff7227fac29d3963a198f271f4ec74b84c1f364bdf2f7964850ecb51c36e30deef5e96c440782e17401",
  },
  {
    index: 2,
    dst_hash: "d73db5a8b0be3b571b40d2b80ff490fe45e135f1992c5863ecb78e25d00ceddb",
    src_hash: "ab7ff601a29bd95610dea57dad100e54d53a837db06604afa3c2eaf482d2a82e",
    src_size: 1440,
    encrypted:
      "601efca604bda1cdcde9e79722e5e71d9fcd5764c0fd52a9d0dbf6aeaec53fc462cbc01a6a372a2247ab7a847538ed8e623609",
  },
];

const decompress = (input) => new Uint8Array(brotliDecompressSync(input));

test("decrypts a native self_encryption 0.36 whole-file vector", async () => {
  const sourceHashes = chunks.map((chunk) => hexToBytes(chunk.src_hash, 32));
  const plaintextChunks = await Promise.all(
    chunks.map((chunk) =>
      decryptSelfEncryptedChunk(chunk, hexToBytes(chunk.encrypted), sourceHashes, 0, decompress),
    ),
  );
  const plaintext = new Uint8Array(
    plaintextChunks.reduce((total, chunk) => total + chunk.length, 0),
  );
  let offset = 0;
  for (const chunk of plaintextChunks) {
    plaintext.set(chunk, offset);
    offset += chunk.length;
  }

  assert.equal(new TextDecoder().decode(plaintext), "browser whole-file fixture\n".repeat(160));
  assert.equal(
    bytesToHex(blake3(plaintext)),
    "e0e422267ac59c56bf032d6d830035d343369d20147dd5f6b63351a29b015f22",
  );
});

test("rejects an authenticated self-encryption chunk after tampering", async () => {
  const sourceHashes = chunks.map((chunk) => hexToBytes(chunk.src_hash, 32));
  const tampered = hexToBytes(chunks[0].encrypted);
  tampered[0] ^= 1;
  await assert.rejects(
    decryptSelfEncryptedChunk(chunks[0], tampered, sourceHashes, 0, decompress),
    /authentication failed/,
  );
});

test("downloads a public DataMap and reconstructs a complete saveable file", async () => {
  const content = new TextEncoder().encode("browser whole-file fixture\n".repeat(160));
  const dataMapContent = new TextEncoder().encode("native public DataMap fixture");
  const dataMapAddress = bytesToHex(blake3(dataMapContent));
  const encryptedByAddress = new Map(
    chunks.map((chunk) => [chunk.dst_hash, hexToBytes(chunk.encrypted)]),
  );
  encryptedByAddress.set(dataMapAddress, dataMapContent);
  const requested = [];
  const downloadChunk = async (_seeds, address) => {
    requested.push(address);
    const bytes = encryptedByAddress.get(address);
    if (!bytes) throw new Error(`No fixture record ${address}`);
    return { content: bytes, node: { peer_id: "11".repeat(32) } };
  };

  const result = await downloadPublicFile(
    [],
    {
      name: "fixture.txt",
      address: dataMapAddress,
      size: content.length,
      content_type: "text/plain",
      blake3: bytesToHex(blake3(content)),
      data_map_size: dataMapContent.length,
      chunks,
    },
    { downloadChunk, decompress },
  );

  assert.deepEqual(result.content, content);
  assert.equal(result.hash, bytesToHex(blake3(content)));
  assert.deepEqual(new Set(requested), new Set([dataMapAddress, ...chunks.map((c) => c.dst_hash)]));
});
