name: ant-core release

on:
  push:
    tags:
      - "ant-core-v*"

env:
  CARGO_TERM_COLOR: always

jobs:
  publish:
    name: publish ant-core to crates.io
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable

      - name: publish ant-core
        working-directory: ant-core
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
        run: cargo publish
